# Generated by Django 3.2.7 on 2021-11-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuotaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='DiscordUser',
        ),
        migrations.AlterField(
            model_name='horasusuario',
            name='promedio',
            field=models.IntegerField(default=0),
        ),
    ]
