# Generated by Django 3.2.6 on 2021-11-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0002_auto_20211120_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuotausuario',
            old_name='fecha',
            new_name='fechaExpiracion',
        ),
        migrations.AddField(
            model_name='cuotausuario',
            name='fechaInicio',
            field=models.DateField(auto_now=True),
        ),
    ]
