# Generated by Django 3.2.6 on 2021-11-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0003_auto_20211121_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuotausuario',
            name='fechaInicio',
            field=models.DateField(),
        ),
    ]
