# Generated by Django 3.2.7 on 2021-11-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0010_alter_usuario_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='passchange_verif_code',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
